const DATA_PATH = "data/recipes.json";
const CONFIG_KEY = "recipe_book_config_v1";
const CART_KEY = "recipe_book_cart_v1";
const TAG_USE_KEY = "recipe_book_tag_use_v1";

const state = { view: "recipes", recipes: [], cart: loadJson(CART_KEY, {}), activeTag: "", query: "", editingId: null, config: loadJson(CONFIG_KEY, { owner: "orchiq0214", repo: "blogs", branch: "main", token: "" }) };
const app = document.querySelector("#app");

function loadJson(key, fallback) { try { return { ...fallback, ...JSON.parse(localStorage.getItem(key) || "{}") }; } catch { return fallback; } }
function save(key, value) { localStorage.setItem(key, JSON.stringify(value)); }
function escapeHtml(value) { return String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;"); }
function numberText(value) { return Number.isInteger(value) ? String(value) : Number(value.toFixed(2)).toString(); }
function cartSize() { return Object.values(state.cart).reduce((total, count) => total + Number(count || 0), 0); }
function toast(message) { const node = document.createElement("div"); node.className = "notice"; node.style.cssText = "position:fixed;left:16px;right:16px;bottom:72px;z-index:20;max-width:500px;margin:auto"; node.textContent = message; document.body.appendChild(node); setTimeout(() => node.remove(), 2400); }

function allTags() { return [...new Set(state.recipes.flatMap((recipe) => recipe.tags || []))]; }
function orderedTags() { const used = loadJson(TAG_USE_KEY, {}); return allTags().sort((a, b) => (used[b] || 0) - (used[a] || 0) || a.localeCompare(b, "zh-CN")); }
function useTag(tag) { if (!tag) return; const used = loadJson(TAG_USE_KEY, {}); used[tag] = (used[tag] || 0) + 1; save(TAG_USE_KEY, used); }
function recipeMatches(recipe) { const needle = state.query.trim().toLowerCase(); return (!state.activeTag || recipe.tags.includes(state.activeTag)) && (!needle || [recipe.name, ...recipe.tags, ...recipe.ingredients.map((item) => item.name)].join(" ").toLowerCase().includes(needle)); }
function formatIngredients(recipe, servings = 1) { return RecipeCore.scaleIngredients(recipe, servings).map((item) => `${item.name} ${numberText(item.amount)}${item.unit}`).join("、"); }

function updateChrome() { document.querySelector("#recipeCount").textContent = `${state.recipes.length} 道菜`; document.querySelector("#cartBadge").textContent = cartSize(); document.querySelectorAll(".nav-item").forEach((node) => node.classList.toggle("active", node.dataset.view === state.view)); }
function renderRecipes() {
  const visible = state.recipes.filter(recipeMatches);
  app.innerHTML = `<input class="search" id="search" value="${escapeHtml(state.query)}" placeholder="搜菜名、食材或标签" />
    <div class="tag-row"><button class="tag ${state.activeTag ? "" : "active"}" data-tag="">全部</button>${orderedTags().map((tag) => `<button class="tag ${tag === state.activeTag ? "active" : ""}" data-tag="${escapeHtml(tag)}">${escapeHtml(tag)}</button>`).join("")}</div>
    <div class="section-line"><span>${state.activeTag || state.query ? `找到 ${visible.length} 道` : "从今天想吃的开始选"}</span><span>加入后在采购单汇总</span></div>
    <section class="recipe-list">${visible.length ? visible.map(renderRecipe).join("") : `<div class="empty">没有找到这道菜</div>`}</section>`;
}
function renderRecipe(recipe) { const count = Number(state.cart[recipe.id] || 0); return `<article class="recipe-card"><div class="recipe-head"><div><h2 class="recipe-title">${escapeHtml(recipe.name)}</h2><div class="mini-tags">${recipe.tags.map((tag) => `<span>${escapeHtml(tag)}</span>`).join("")}</div></div><span>${count ? `已选 ${count} 份` : ""}</span></div><div class="ingredients">食材：${escapeHtml(formatIngredients(recipe))}</div><div class="seasonings">调料：${escapeHtml(recipe.seasonings.join("、"))}</div><div class="card-actions"><button class="secondary" data-action="edit" data-id="${recipe.id}">编辑</button><button class="primary" data-action="add" data-id="${recipe.id}">${count ? "再加一份" : "加入采购单"}</button></div></article>`; }
function renderCart() { const selected = state.recipes.filter((recipe) => state.cart[recipe.id]); const shopping = RecipeCore.buildShoppingList(state.recipes, state.cart); app.innerHTML = selected.length ? `<section class="panel"><h2>这次要做</h2>${selected.map((recipe) => `<div class="cart-row"><div><strong>${escapeHtml(recipe.name)}</strong><div class="ingredients">${escapeHtml(formatIngredients(recipe, state.cart[recipe.id]))}</div></div><div class="qty"><button data-action="decrease" data-id="${recipe.id}" aria-label="减少一份">−</button><b>${state.cart[recipe.id]} 份</b><button data-action="add" data-id="${recipe.id}" aria-label="增加一份">＋</button></div></div>`).join("")}</section><section class="shopping-list"><h2>采购清单</h2><ul>${shopping.map((item) => `<li>${escapeHtml(item.name)} ${numberText(item.amount)}${escapeHtml(item.unit)}</li>`).join("")}</ul><p class="ingredients">调料不计量，也不会加入采购单。</p><button class="secondary" data-action="copy">复制清单</button></section>` : `<div class="empty">还没有选菜<br><br><button class="primary" data-view-jump="recipes">去选菜</button></div>`; }
function editorFields(recipe = {}) { const ingredients = recipe.ingredients?.length ? recipe.ingredients : [{ name: "", amount: "", unit: "g" }]; return `<form id="recipeForm" class="form"><div class="field"><label>菜名</label><input name="name" required value="${escapeHtml(recipe.name || "")}" placeholder="例如：盐葱牛肉" /></div><div class="field"><label>标签（用中文逗号或英文逗号分开，可直接输入新标签）</label><input name="tags" required value="${escapeHtml((recipe.tags || []).join("、"))}" placeholder="牛肉、咸鲜、快手菜" /></div><section class="panel"><h2>食材</h2><div id="ingredientRows">${ingredients.map(ingredientRow).join("")}</div><button class="secondary" type="button" data-action="add-ingredient">添加食材</button></section><div class="field"><label>调料种类（不填分量，不进采购单）</label><input name="seasonings" value="${escapeHtml((recipe.seasonings || []).join("、"))}" placeholder="盐、生抽、蚝油" /></div><div><button class="primary" type="submit">保存到本机</button> <button class="secondary" type="button" data-action="save-github">保存并同步 GitHub</button></div></form>`; }
function ingredientRow(item = {}) { return `<div class="ingredient-row"><input name="ingredientName" required value="${escapeHtml(item.name || "")}" placeholder="食材" /><input name="ingredientAmount" required inputmode="decimal" value="${escapeHtml(item.amount ?? "")}" placeholder="数量" /><input name="ingredientUnit" required value="${escapeHtml(item.unit || "g")}" placeholder="单位" /><button class="delete" type="button" data-action="remove-ingredient">删除</button></div>`; }
function renderEditor() { const recipe = state.recipes.find((item) => item.id === state.editingId); app.innerHTML = `<div class="section-line"><span>${recipe ? "编辑菜谱" : "新增菜谱"}</span>${recipe ? `<button class="delete" data-action="new-recipe">取消编辑</button>` : ""}</div>${editorFields(recipe)}`; }
function renderSettings() { const modal = document.createElement("div"); modal.className = "modal"; modal.id = "settingsModal"; modal.innerHTML = `<section class="panel"><div class="recipe-head"><h2>GitHub 同步</h2><button class="icon-button" data-action="close-settings" aria-label="关闭">×</button></div><p class="ingredients">令牌只保存在这台设备的浏览器里，用来把公开菜谱数据写回仓库。</p><form class="form" id="settingsForm"><div class="field"><label>GitHub 用户名</label><input name="owner" value="${escapeHtml(state.config.owner)}" required /></div><div class="field"><label>仓库名</label><input name="repo" value="${escapeHtml(state.config.repo)}" required /></div><div class="field"><label>分支</label><input name="branch" value="${escapeHtml(state.config.branch)}" required /></div><div class="field"><label>GitHub token</label><input name="token" type="password" value="${escapeHtml(state.config.token)}" placeholder="只保存在当前浏览器" /></div><button class="primary" type="submit">保存设置</button></form></section>`; document.body.appendChild(modal); }
function render() { updateChrome(); if (state.view === "recipes") renderRecipes(); if (state.view === "cart") renderCart(); if (state.view === "editor") renderEditor(); }

function saveLocalRecipes() { localStorage.setItem("recipe_book_recipes_v1", JSON.stringify(state.recipes)); }
function recipeFromForm(form) { const data = new FormData(form); const names = data.getAll("ingredientName"), amounts = data.getAll("ingredientAmount"), units = data.getAll("ingredientUnit"); const ingredients = names.map((name, index) => ({ name: name.trim(), amount: Number(amounts[index]), unit: units[index].trim() })).filter((item) => item.name && Number.isFinite(item.amount) && item.amount > 0 && item.unit); return { id: state.editingId || `recipe-${Date.now().toString(36)}`, name: data.get("name").trim(), tags: RecipeCore.mergeTags([], String(data.get("tags")).split(/[、,，]/)), ingredients, seasonings: RecipeCore.mergeTags([], String(data.get("seasonings") || "").split(/[、,，]/)) }; }
function commitRecipe(recipe) { const index = state.recipes.findIndex((item) => item.id === recipe.id); if (index >= 0) state.recipes[index] = recipe; else state.recipes.unshift(recipe); state.editingId = recipe.id; saveLocalRecipes(); }
async function syncToGithub() { if (!state.config.token) throw new Error("请先在设置中填写 GitHub token"); const path = DATA_PATH.split("/").map(encodeURIComponent).join("/"); const base = `https://api.github.com/repos/${encodeURIComponent(state.config.owner)}/${encodeURIComponent(state.config.repo)}/contents/${path}`; const remote = await fetch(`${base}?ref=${encodeURIComponent(state.config.branch)}`, { headers: { Accept: "application/vnd.github+json", Authorization: `Bearer ${state.config.token}` } }); if (!remote.ok) throw new Error("读取 GitHub 数据失败，请检查 token 和仓库设置"); const file = await remote.json(); const content = btoa(unescape(encodeURIComponent(JSON.stringify(state.recipes, null, 2)))); const response = await fetch(base, { method: "PUT", headers: { Accept: "application/vnd.github+json", Authorization: `Bearer ${state.config.token}`, "Content-Type": "application/json" }, body: JSON.stringify({ message: "feat: update recipe book", content, sha: file.sha, branch: state.config.branch }) }); if (!response.ok) { const detail = await response.json().catch(() => ({})); throw new Error(detail.message || "同步失败"); } }

document.addEventListener("click", async (event) => { const target = event.target.closest("[data-action], [data-view], [data-view-jump], [data-tag]"); if (!target) return; if (target.dataset.view || target.dataset.viewJump) { state.view = target.dataset.view || target.dataset.viewJump; state.editingId = null; render(); return; } if (target.dataset.tag !== undefined) { state.activeTag = target.dataset.tag; useTag(state.activeTag); render(); return; } const id = target.dataset.id; if (target.dataset.action === "add") { state.cart[id] = (state.cart[id] || 0) + 1; save(CART_KEY, state.cart); render(); } if (target.dataset.action === "decrease") { state.cart[id] -= 1; if (!state.cart[id]) delete state.cart[id]; save(CART_KEY, state.cart); render(); } if (target.dataset.action === "edit") { state.editingId = id; state.view = "editor"; render(); } if (target.dataset.action === "new-recipe") { state.editingId = null; render(); } if (target.dataset.action === "add-ingredient") document.querySelector("#ingredientRows").insertAdjacentHTML("beforeend", ingredientRow()); if (target.dataset.action === "remove-ingredient") target.closest(".ingredient-row").remove(); if (target.dataset.action === "open-settings") renderSettings(); if (target.dataset.action === "close-settings") document.querySelector("#settingsModal")?.remove(); if (target.dataset.action === "copy") { const text = RecipeCore.buildShoppingList(state.recipes, state.cart).map((item) => `${item.name} ${numberText(item.amount)}${item.unit}`).join("\n"); await navigator.clipboard.writeText(text); toast("采购清单已复制"); } if (target.dataset.action === "save-github") { const form = document.querySelector("#recipeForm"); if (!form.reportValidity()) return; const recipe = recipeFromForm(form); commitRecipe(recipe); try { await syncToGithub(); toast("已保存并同步到 GitHub"); } catch (error) { toast(error.message); } render(); } });
document.addEventListener("input", (event) => { if (event.target.id === "search") { state.query = event.target.value; renderRecipes(); } });
document.addEventListener("submit", (event) => { event.preventDefault(); if (event.target.id === "recipeForm") { const recipe = recipeFromForm(event.target); commitRecipe(recipe); toast("已保存到本机，可在设置中同步到 GitHub"); render(); } if (event.target.id === "settingsForm") { state.config = Object.fromEntries(new FormData(event.target)); save(CONFIG_KEY, state.config); document.querySelector("#settingsModal")?.remove(); toast("同步设置已保存"); } });
(async function boot() { const cached = localStorage.getItem("recipe_book_recipes_v1"); try { state.recipes = cached ? JSON.parse(cached) : await (await fetch(DATA_PATH)).json(); } catch { state.recipes = cached ? JSON.parse(cached) : []; } render(); })();
